# Generated by Django 5.1.5 on 2025-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(help_text='Unique ID for the employee', max_length=10, unique=True)),
                ('role', models.CharField(choices=[('Shift Technician', 'Shift Technician'), ('Manufacturing Technician', 'Manufacturing Technician'), ('General Operator', 'General Operator'), ('General Support Operator', 'General Support Operator')], max_length=50)),
                ('date_joined', models.DateField(help_text='Date the employee joined the company')),
            ],
        ),
    ]
