# Generated by Django 5.1.5 on 2025-02-03 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0003_alter_workarea_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(help_text='Unique Employee ID', max_length=10, unique=True)),
                ('role', models.CharField(choices=[('Shift Technician', 'Shift Technician'), ('Manufacturing Technician', 'Manufacturing Technician'), ('General Operator', 'General Operator'), ('General Support Operator', 'General Support Operator')], help_text='Employee Role', max_length=50)),
                ('shift', models.ForeignKey(blank=True, help_text='Default assigned shift', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift')),
            ],
        ),
    ]
