# Generated by Django 5.1.5 on 2025-02-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Red', 'Red Shift'), ('Green', 'Green Shift'), ('Blue', 'Blue Shift'), ('Yellow', 'Yellow Shift')], max_length=10, unique=True)),
                ('start_date', models.DateField(help_text='The date when this shift starts')),
                ('cycle_length', models.PositiveIntegerField(default=16, help_text='Length of the shift cycle in days')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The actual date of this shift')),
                ('shift_type', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift'), ('Off', 'Off')], max_length=10)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
            options={
                'unique_together': {('shift', 'date')},
            },
        ),
    ]
