# Generated by Django 5.1.5 on 2025-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField(help_text='Production line number (e.g., 1, 2, 3, 4, MOH, Shared)')),
                ('name', models.CharField(help_text='Name of the work area (e.g., Process, Multipack, Palletiser)', max_length=50)),
                ('subwork_area', models.CharField(help_text='Specific task area (e.g., Fryer Operator, Zone Runner)', max_length=50)),
                ('required_employees', models.PositiveIntegerField(default=1, help_text='Number of employees required for this work area')),
                ('employee_type', models.CharField(help_text='Type of employee needed (e.g., General Operator, Manufacturing Technician)', max_length=50)),
                ('task_type', models.CharField(choices=[('Operational', 'Operational'), ('Overhead', 'Overhead')], help_text='Defines if the task is Operational or Overhead', max_length=20)),
            ],
        ),
    ]
