# Generated by Django 5.1.5 on 2025-02-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employee_id'),
        ('shifts', '0003_alter_workarea_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(help_text='Employee assigned to this work area.', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('shift_pattern', models.ForeignKey(help_text='Shift pattern for this allocation.', on_delete=django.db.models.deletion.CASCADE, to='shifts.shiftpattern')),
                ('work_area', models.ForeignKey(help_text='Work area where the employee is assigned.', on_delete=django.db.models.deletion.CASCADE, to='shifts.workarea')),
            ],
        ),
    ]
